version: "3"
services:
  node:
    restart: always
    build: .
    environment:
      - MONGO_URL="mongodb://mongo:27017/open-pay-db"
      - PORT=8001
      - SETUP_TEST_USERS=true
    ports:
      - 8001:8001
    volumes:
      - ./:/code
  mongo:
    image: mongo:4.4.5
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
