name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: List files in the client
        working-directory: ./client
        run: |
          ls
      - name: Build React Client
        working-directory: ./client
        run: |
          sh ./buildClient.sh
      - name: Docker compose up
        working-directory: ./server
        run: |
          docker-compose up -d
      - name: Docker list
        working-directory: ./server
        run: |
          docker ps
      - name: Server Install
        working-directory: ./server
        run: |
          npm install
      - name: Test server
        working-directory: ./server
        run: |
          npm run test
      - name: Test server
        working-directory: ./client
        run: |
          npm run cy:run
